services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Marketplace2026!"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Marketplace2026!", "-Q", "SELECT 1", "-No"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build:
      context: ./ServiceMarketplace.API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=ServiceMarketplaceDb;User Id=sa;Password=Marketplace2026!;TrustServerCertificate=True;Encrypt=False;"
      ConnectionStrings__Redis: "alert-aphid-34752.upstash.io:6379,password=AYfAAAIncDI4MDdiMzc3ZTFmOGM0OWFmOWYzNTRiYzI5NmE0NWIyY3AyMzQ3NTI,ssl=True,abortConnect=False"
      Jwt__Key: "your-secret-key-minimum-32-characters-long!!"
      Jwt__Issuer: "ServiceMarketplace"
      Jwt__Audience: "ServiceMarketplaceClient"
      HuggingFace__ApiKey: "${HUGGINGFACE_API_KEY}"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./service-marketplace-client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  sqldata:
  redisdata:
